unify platform.target to ubuntu-based system
Signed-off-by: Austin Liu <austin362667@gmail.com>

unify platform.target to ubuntu-based system

Signed-off-by: Austin Liu <austin362667@gmail.com>

unify platform.target system detection

Signed-off-by: Austin Liu <austin362667@gmail.com>

diff --git a/.github/workflows/flyteidl-nightly.yml b/.github/workflows/flyteidl-nightly.yml
--- a/.github/workflows/flyteidl-nightly.yml
+++ b/.github/workflows/flyteidl-nightly.yml
@@ -48,32 +48,40 @@ jobs:
           target: ${{ matrix.platform.target }}
           command: build
           args: --release --out dist --find-interpreter -m flyteidl/Cargo.toml
+          sccache: 'true'
+          manylinux: auto
           before-script-linux: |
             echo "Starting before-script-linux for target: ${{ matrix.platform.target }}"
-            case "${{ matrix.platform.target }}" in
-              "aarch64" | "armv7" | "s390x" | "ppc64le")
-                echo "Running on a Debian-based system"
-                # NOTE: pypa/manylinux docker images are Debian based
-                sudo apt update
-                # NOTE: install openssl deps
-                sudo apt install -y pkg-config libssl-dev
-                # NOTE: install protoc deps
-                sudo apt install -y protobuf-compiler libprotobuf-dev
-                # NOTE: generate rust protobuf
-                (cd ${{ github.workspace }}/flyteidl && rm -rf ./gen/pb_rust/* && cargo run --bin gen_flyteidl)
-                ;;
-              "x86" | "x86_64")
-                echo "Running on a CentOS-based system"
-                # NOTE: rust-cross/manylinux docker images are CentOS based
-                yum update -y
-                # NOTE: install openssl deps
-                yum install -y openssl openssl-devel
-                # NOTE: install protoc deps
-                yum install -y protobuf protobuf-devel
-                # NOTE: generate rust protobuf
-                (cd ${{ github.workspace }}/flyteidl && rm -rf ./gen/pb_rust/* && cargo run --bin gen_flyteidl)
-                ;;
-            esac
+
+            # Detect OS type
+            if [ -f /etc/os-release ]; then
+              . /etc/os-release
+              case "$ID" in
+                debian|ubuntu)
+                  echo "Running on a Debian-based system"
+                  sudo apt update
+                  sudo apt install -y pkg-config libssl-dev protobuf-compiler libprotobuf-dev
+                  ;;
+                centos|rhel|fedora)
+                  echo "Running on a CentOS-based system"
+                  sudo yum update -y
+                  sudo yum install -y openssl openssl-devel protobuf protobuf-devel
+                  ;;
+                *)
+                  echo "Unsupported distribution: $ID"
+                  exit 1
+                  ;;
+              esac
+            else
+              echo "Cannot determine the operating system type."
+              exit 1
+            fi
+
+            # Generate Rust protobuf
+            (cd ${{ github.workspace }}/flyteidl && rm -rf ./gen/pb_rust/* && cargo run --bin gen_flyteidl)
+
+            echo "Completed before-script-linux for target: ${{ matrix.platform.target }}"
+
       - name: Upload wheels
         uses: actions/upload-artifact@v4
         with:
