fix ci
Signed-off-by: Kevin Su <pingsutw@apache.org>

diff --git a/.github/workflows/helm-charts.yaml b/.github/workflows/helm-charts.yaml
--- a/.github/workflows/helm-charts.yaml
+++ b/.github/workflows/helm-charts.yaml
@@ -1,6 +1,7 @@
 name: Package & Push Flyte Helm Charts
 
 on:
+  pull_request:
   push:
     branches:
       - master
@@ -25,11 +26,20 @@ jobs:
           registry: ghcr.io
           username: "${{ secrets.FLYTE_BOT_USERNAME }}"
           password: "${{ secrets.FLYTE_BOT_PAT }}"
-      - name: Publish Helm chart to GHCR
+      - name: Build helm chart
         working-directory: charts
         run: |
           helm package \
             --app-version=${{ github.sha }} \
             --version=0.0-${{ github.sha }} \
             ${{ matrix.chart }}
+          
+          if ! ls ${{ matrix.chart }}-* 2>&1 >/dev/null;
+          then
+              echo "Chart package not found."
+              exit 1
+          fi
+      - name: Publish Helm chart to GHCR
+        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
+        run:
           helm push ${{ matrix.chart }}-*.tgz oci://ghcr.io/flyteorg/helm-charts
